services:
  maketrack:
    image: ghcr.io/bdoster/maketrack:latest
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./maketrack-data:/data
      - ./maketrack-uploads:/uploads
    environment:
      - TZ=America/Los_Angeles
      - MAKETRACK_LOG_LEVEL=INFO
